### ISSUE TITLE
The dashboard freezes and CPU utilisation grows

### ISSUE THREAD

**Issue by l29ah** [cyrus-and/gdb-dashboard#203] opened 2020-05-20 00:00 UTC

**Comment by cyrus-and** [comment] 2020-05-20 07:20
Cannot reproduce, it would be great if you could provide a more detailed bug report, possibly with an example program....

**Comment by l29ah** [comment] 2020-05-20 11:45
Build freeoriond. Run `gdb --args ./freeoriond --hostless  -q --setup.ai.player.count 0`. Wait for it to do its init business (CPU utilization dropping to zero, memory consumption stopping growing). Crash it with `socat 'tcp6:[::1]:12346' stdio < /dev/urandom`. Hit `up` until you get to some sensible position like `ExtractJoinGameMessageData`. Hit `dashboard`. Observe gdb stopping responding, while CPU and memory utilization of the child process growing again.

**Comment by l29ah** [comment] 2020-05-20 11:51
Probably freeoriond from the binary release of freeorion is good as well.

**Comment by cyrus-and** [comment] 2020-05-20 12:35
> Observe gdb stopping responding, while CPU and memory utilization of the child process growing again.

This is yet another problem, it doesn't necessarily means that the program is resumed, rather it's entirely possible that some of the modules is having too much work to do. It is likely the Assembler module, that is trying to parse a *huge* function.

Could you please try if that's the case by disabling that module before doing the above steps?

**Comment by cyrus-and** [comment] 2020-07-25 11:58
Closing as this could be addressed in e44418fa8b610ca1559ea22c980703b98c420784 in case this issue is a duplicate of #208 and #210. Feel free to reopen if that's not the case.

**Closed by cyrus-and** 2020-07-25 11:58 UTC
Labels: bug, irreproducible
