### ISSUE TITLE
Terminal display error / bug 

### ISSUE THREAD

**Issue by FranciscoCross** [cyrus-and/gdb-dashboard#240] opened 2021-05-14 22:07 UTC
Hello, I have the problem that the elements are not displayed as they should. I can't find a solution to this problem and I know several people who have the same problem, thank you in advance! Greetings!!!
![image](https://user-images.githubusercontent.com/63804936/118336024-46035280-b4e7-11eb-9fb3-d5b6f188b3d8.png)

**Comment by cyrus-and** [comment] 2021-05-15 07:12
Hi! A full screenshot would be useful.

I suspect that this is a duplicate of #204, and #221 might provide a solution. If that's the case it's still unclear to me why GDB sometime shows special registers, it never occurred to me...

**Comment by FranciscoCross** [comment] 2021-05-15 16:46
Thank you very much seeing the other issues I was able to solve it, thanks again
I leave the solution:
**`dashboard registers -style list 'rax rbx rcx rdx rsi rdi rbp rsp r8 r9 r10 r11 r12 r13 r14 r15 rip eflags cs ss ds es fs gs'`**
Greetings!!!

**Closed** 2021-05-15 16:48 UTC
Labels: duplicate, not a bug
