### ISSUE TITLE
Bug in registers viewer

### ISSUE THREAD

**Issue by growlnx** [cyrus-and/gdb-dashboard#181] opened 2020-01-12 00:54 UTC
Hello everybody!

I believe have found a bug in the registers viewer.

### Steps to reproduce:

1. A simple Boot Sector program:

```assembly
[org 0x7c00]
[bits 16]

%define NULL 0x00

%define NEWLINE 0x0a
%define RETURN 0x0d

%define BIOS_VIDEO 0x10
%define BIOS_VIDEO_TTY 0x0e

sub_start:
  mov si, cstr_hello_world
  call sub_pcstr

sub_end:
  jmp $; To Infinity and Beyond!

sub_pcstr: ; print cstring subroutine
  mov ah, BIOS_VIDEO_TTY
  pcstr_1:
    lodsb
    or al, NULL
    jnz pcstr_2
    ret
  pcstr_2:
    int BIOS_VIDEO
    jmp pcstr_1

cstr_hello_world: db "hello world!",NEWLINE,RETURN,NULL

times 510-($-$$) db 0x00 ; padding
dw 0xaa55 ; magic
```

![compilation](https://user-images.githubusercontent.com/29213920/72212426-ab41d080-34ba-11ea-835d-f4d9a7b4c4d1.png)

2. Emulating

```
$ qemu-system-i386 hello-world.bin -S -s
```

3. Debugging

![no_registers_remote_debug_8086_bare_metal](https://user-images.githubusercontent.com/29213920/72212447-2905dc00-34bb-11ea-88c2-b0e96f63ff4d.png)

As you can see, no registers are not displayed here, but...

![registers_remote_debug_8086_bare_metal](https://user-images.githubusercontent.com/29213920/72212456-4a66c800-34bb-11ea-95a8-ef9a44c861be.png)

OBS.: My program seems to work fine :grimacing:

![this_works](https://user-images.githubusercontent.com/29213920/72212460-65d1d300-34bb-11ea-8a40-561f2bf53c7d.png)

**Comment by cyrus-and** [comment] 2020-01-12 20:22
Hey!

I'm unable to reproduce this, everything works fine:

```console
$ qemu-system-i386 -S -s -drive format=raw,file=hello-world.bin
```

Then:

```
$ gdb
>>> target remote localhost:1234
─── Output/messages ───────────────────────────────────────
Breakpoint 1, 0x00007c00 in ?? ()
─── Assembly ──────────────────────────────────────────────
!0x00007c00  ? mov    esi,0x2e87c14
 0x00007c05  ? add    bl,ch
 0x00007c07  ? (bad)
 0x00007c08  ? mov    ah,0xe
 0x00007c0a  ? lods   al,BYTE PTR ds:[esi]
 0x00007c0b  ? or     al,0x0
 0x00007c0d  ? jne    0x7c10
 0x00007c0f  ? ret
 0x00007c10  ? int    0x10
 0x00007c12  ? jmp    0x7c0a
─── Breakpoints ───────────────────────────────────────────
[1] break at 0x00007c00 for *0x00007c00 hit 1 time
─── Expressions ───────────────────────────────────────────
─── History ───────────────────────────────────────────────
─── Memory ────────────────────────────────────────────────
─── Notes ─────────────────────────────────────────────────
─── Registers ─────────────────────────────────────────────
      eax 0x0000aa55    ecx 0x00000000    edx 0x00000080
      ebx 0x00000000    esp 0x00006f04    ebp 0x00000000
      esi 0x00000000    edi 0x00000000    eip 0x00007c00
   eflags [ IF ]         cs 0x00000000     ss 0x00000000
       ds 0x00000000     es 0x00000000     fs 0x00000000
       gs 0x00000000
─── Source ────────────────────────────────────────────────
─── Stack ─────────────────────────────────────────────────
[0] from 0x00007c00
─── Threads ───────────────────────────────────────────────
[1] id 1 from 0x00007c00
─── Variables ─────────────────────────────────────────────
───────────────────────────────────────────────────────────
```

And actually it's pretty weird that error, the only way to have a `}` on that line:

https://github.com/cyrus-and/gdb-dashboard/blob/35f30a4b8502c6ef6ffdc73fae1ee9a3ac54d74e/.gdbinit#L1893

is that `name` (a register name) contains a `}`.

**Comment by growlnx** [comment] 2020-01-12 22:57
Hi @cyrus-and !

Hmm... its strange.

I did this litle change in the source for debugging prupurses.

![change_for_debug](https://user-images.githubusercontent.com/29213920/72226450-21543f00-3570-11ea-9791-230494ed336e.png)

And there is a register with '}' as name for me.

![wtf_register](https://user-images.githubusercontent.com/29213920/72226471-519bdd80-3570-11ea-94d7-4ba54f776fce.png)

I added a [check](https://github.com/cyrus-and/gdb-dashboard/blob/35f30a4b8502c6ef6ffdc73fae1ee9a3ac54d74e/.gdbinit#L1891) for '}' similar to '.' and the gdb error msg goes out. 

Now the Register Viewer Format goes crazy. :open_mouth:

![registers_goes_crazy](https://user-images.githubusercontent.com/29213920/72226787-adb43100-3573-11ea-82b5-2903561cb8ba.png)

Debugging a local C program still works fine, apparently.

![cool_registers](https://user-images.githubusercontent.com/29213920/72226897-1d76eb80-3575-11ea-8238-90c55177e19d.png)

**Comment by cyrus-and** [comment] 2020-01-12 23:24
What version of GDB do you have?

**Comment by growlnx** [comment] 2020-01-12 23:30
![gdb_v](https://user-images.githubusercontent.com/29213920/72227356-4fd71780-357a-11ea-9c89-75c638805189.png)

**Comment by growlnx** [comment] 2020-01-12 23:33
> What version of GDB do you have?

![gdb_v](https://user-images.githubusercontent.com/29213920/72227386-bb20e980-357a-11ea-8b41-a8384ccccb7e.png)

**Comment by cyrus-and** [comment] 2020-01-12 23:33
What if you run `info registers` when you get that error?

**Comment by growlnx** [comment] 2020-01-12 23:38
> What if you run `info registers` when you get that error?

hmm... there '{' and '}' in output, looks like a parsing error.

![possible_parsing_err](https://user-images.githubusercontent.com/29213920/72227439-59ad4a80-357b-11ea-9769-58ab2166b788.png)

**Comment by cyrus-and** [comment] 2020-01-12 23:43
For some reason your output of `info registers` is more similar to the output of *my* `info all-registers`, this is weird and I'm not sure why is that, I'm going to try with GDB version 8.3 soon but I doubt that's the reason... In the mean time you can fix this with:

    dashboard registers -style list 'eax ecx edx ebx esp ebp esi edi eip eflags cs ss ds es fs gs'

**Comment by cyrus-and** [comment] 2020-01-13 00:04
> I'm going to try with GDB version 8.3 soon but I doubt that's the reason...

Yeah I get the same output...

**Comment by cyrus-and** [comment] 2020-01-13 12:42
I changed how I fetch the default list of registers, would you mind trying the latest version? (Without the [aforementioned][1] workaround.)

[1]: https://github.com/cyrus-and/gdb-dashboard/issues/181#issuecomment-573471268

**Comment by growlnx** [comment] 2020-01-13 14:14
> I changed how I fetch the default list of registers, would you mind trying the latest version? (Without the [aforementioned](https://github.com/cyrus-and/gdb-dashboard/issues/181#issuecomment-573471268) workaround.)

the register viewer maintains a strange formatting to me.

![still](https://user-images.githubusercontent.com/29213920/72261972-af720900-35f4-11ea-9b9d-f2e4cca2a6e6.png)

I believe it is easier to use the `` >>> info registers``` command and add the first item on each line to registers_list until you find '{' on the line.

**Comment by cyrus-and** [comment] 2020-01-13 14:16
Can you please show me the full output of `maintenance print register-groups`?

**Comment by growlnx** [comment] 2020-01-13 14:19
> Can you please show me the full output of `maintenance print register-groups`?

```console
>>> maintenance print register-groups
 Name         Nr  Rel Offset    Size  Type            Groups
 eax           0    0      0       4 int32_t         general,all,save,restore
 ecx           1    1      4       4 int32_t         general,all,save,restore
 edx           2    2      8       4 int32_t         general,all,save,restore
 ebx           3    3     12       4 int32_t         general,all,save,restore
 esp           4    4     16       4 *1              general,all,save,restore
 ebp           5    5     20       4 *1              general,all,save,restore
 esi           6    6     24       4 int32_t         general,all,save,restore
 edi           7    7     28       4 int32_t         general,all,save,restore
 eip           8    8     32       4 *1              general,all,save,restore
 eflags        9    9     36       4 i386_eflags     general,all,save,restore
 cs           10   10     40       4 int32_t         general,all,save,restore
 ss           11   11     44       4 int32_t         general,all,save,restore
 ds           12   12     48       4 int32_t         general,all,save,restore
 es           13   13     52       4 int32_t         general,all,save,restore
 fs           14   14     56       4 int32_t         general,all,save,restore
 gs           15   15     60       4 int32_t         general,all,save,restore
 st0          16   16     64      10 _i387_ext       float,all,save,restore
 st1          17   17     74      10 _i387_ext       float,all,save,restore
 st2          18   18     84      10 _i387_ext       float,all,save,restore
 st3          19   19     94      10 _i387_ext       float,all,save,restore
 st4          20   20    104      10 _i387_ext       float,all,save,restore
 st5          21   21    114      10 _i387_ext       float,all,save,restore
 st6          22   22    124      10 _i387_ext       float,all,save,restore
 st7          23   23    134      10 _i387_ext       float,all,save,restore
 fctrl        24   24    144       4 long            float,all,save,restore
 fstat        25   25    148       4 long            float,all,save,restore
 ftag         26   26    152       4 long            float,all,save,restore
 fiseg        27   27    156       4 long            float,all,save,restore
 fioff        28   28    160       4 long            float,all,save,restore
 foseg        29   29    164       4 long            float,all,save,restore
 fooff        30   30    168       4 long            float,all,save,restore
 fop          31   31    172       4 long            float,all,save,restore
 ''           32   32    176       0 int0_t          general
 ''           33   33    176       0 int0_t          general
 ''           34   34    176       0 int0_t          general
 ''           35   35    176       0 int0_t          general
 ''           36   36    176       0 int0_t          general
 ''           37   37    176       0 int0_t          general
 ''           38   38    176       0 int0_t          general
 ''           39   39    176       0 int0_t          general
 ''           40   40    176       0 int0_t          general
 ''           41   41    176       0 int0_t          general
 ''           42   42    176       0 int0_t          general
 ''           43   43    176       0 int0_t          general
 ''           44   44    176       0 int0_t          general
 ''           45   45    176       0 int0_t          general
 ''           46   46    176       0 int0_t          general
 ''           47   47    176       0 int0_t          general
 ''           48   48    176       0 int0_t          general
 ''           49   49    176       0 int0_t          general
 ''           50   50    176       0 int0_t          general
 ''           51   51    176       0 int0_t          general
 ''           52   52    176       0 int0_t          general
 ''           53   53    176       0 int0_t          general
 ''           54   54    176       0 int0_t          general
 ''           55   55    176       0 int0_t          general
 ''           56   56    176       0 int0_t          general
 ''           57   57    176       0 int0_t          general
 ''           58   58    176       0 int0_t          general
 ''           59   59    176       0 int0_t          general
 ''           60   60    176       0 int0_t          general
 ''           61   61    176       0 int0_t          general
 ''           62   62    176       0 int0_t          general
 ''           63   63    176       0 int0_t          general
 ''           64   64    176       0 int0_t          general
 ''           65   65    176       0 int0_t          general
 ''           66   66    176       0 int0_t          general
 ''           67   67    176       0 int0_t          general
 ''           68   68    176       0 int0_t          general
 ''           69   69    176       0 int0_t          general
 ''           70   70    176       0 int0_t          general
 ''           71   71    176       0 int0_t          general
 ''           72   72    176       0 int0_t          general
 fs_base      73   73    176       4 int32_t         general,all,save,restore
 gs_base      74   74    180       4 int32_t         general,all,save,restore
 k_gs_base    75   75    184       4 int32_t         general,all,save,restore
 cr0          76   76    188       4 i386_cr0        general,all,save,restore
 cr2          77   77    192       4 int32_t         general,all,save,restore
 cr3          78   78    196       4 i386_cr3        general,all,save,restore
 cr4          79   79    200       4 i386_cr4        general,all,save,restore
 cr8          80   80    204       4 int32_t         general,all,save,restore
 efer         81   81    208       8 i386_efer       general,all,save,restore
 xmm0         82   82    216      16 vec128          general,all,save,restore
 xmm1         83   83    232      16 vec128          general,all,save,restore
 xmm2         84   84    248      16 vec128          general,all,save,restore
 xmm3         85   85    264      16 vec128          general,all,save,restore
 xmm4         86   86    280      16 vec128          general,all,save,restore
 xmm5         87   87    296      16 vec128          general,all,save,restore
 xmm6         88   88    312      16 vec128          general,all,save,restore
 xmm7         89   89    328      16 vec128          general,all,save,restore
 mxcsr        90   90    344       4 i386_mxcsr      general,all,save,restore
 al           91    0    348       1 int8_t          
 cl           92    1    349       1 int8_t          
 dl           93    2    350       1 int8_t          
 bl           94    3    351       1 int8_t          
 ah           95    4    352       1 int8_t          
 ch           96    5    353       1 int8_t          
 dh           97    6    354       1 int8_t          
 bh           98    7    355       1 int8_t          
 ax           99    8    356       2 int16_t         
 cx          100    9    358       2 int16_t         
 dx          101   10    360       2 int16_t         
 bx          102   11    362       2 int16_t         
 ''          103   12    364       2 int16_t         
 bp          104   13    366       2 int16_t         
 si          105   14    368       2 int16_t         
 di          106   15    370       2 int16_t         
 mm0         107   16    372       8 _vec64i         mmx,all,vector
 mm1         108   17    380       8 _vec64i         mmx,all,vector
 mm2         109   18    388       8 _vec64i         mmx,all,vector
 mm3         110   19    396       8 _vec64i         mmx,all,vector
 mm4         111   20    404       8 _vec64i         mmx,all,vector
 mm5         112   21    412       8 _vec64i         mmx,all,vector
 mm6         113   22    420       8 _vec64i         mmx,all,vector
 mm7         114   23    428       8 _vec64i         mmx,all,vector
*1: Register type's name NULL.
```

**Comment by cyrus-and** [comment] 2020-01-13 14:24
So the problem is that your GDB instance is considering the following registers as *general*, which is clearly not the case:

```
 fs_base      73   73    176       4 int32_t         general,all,save,restore
 gs_base      74   74    180       4 int32_t         general,all,save,restore
 k_gs_base    75   75    184       4 int32_t         general,all,save,restore
 cr0          76   76    188       4 i386_cr0        general,all,save,restore
 cr2          77   77    192       4 int32_t         general,all,save,restore
 cr3          78   78    196       4 i386_cr3        general,all,save,restore
 cr4          79   79    200       4 i386_cr4        general,all,save,restore
 cr8          80   80    204       4 int32_t         general,all,save,restore
 efer         81   81    208       8 i386_efer       general,all,save,restore
 xmm0         82   82    216      16 vec128          general,all,save,restore
 xmm1         83   83    232      16 vec128          general,all,save,restore
 xmm2         84   84    248      16 vec128          general,all,save,restore
 xmm3         85   85    264      16 vec128          general,all,save,restore
 xmm4         86   86    280      16 vec128          general,all,save,restore
 xmm5         87   87    296      16 vec128          general,all,save,restore
 xmm6         88   88    312      16 vec128          general,all,save,restore
 xmm7         89   89    328      16 vec128          general,all,save,restore
 mxcsr        90   90    344       4 i386_mxcsr      general,all,save,restore
```

I think you should file an issue to the GDB bug tracker and use the [above][1] workaround.

Thanks for the accurate report.

[1]: https://github.com/cyrus-and/gdb-dashboard/issues/181#issuecomment-573471268

**Comment by cyrus-and** [comment] 2020-01-15 09:45
So I'm closing this, feel free to post here the link to the upstream issue (in case you decide to file it) or anything else you may want to add.

**Closed by cyrus-and** 2020-01-15 09:45 UTC
