### ISSUE TITLE
A problem internal to GDB has been detected, further debugging may prove unreliable.

### ISSUE THREAD

**Issue by zkrx** [cyrus-and/gdb-dashboard#186] opened 2020-02-21 09:01 UTC
I'm honestly not sure that this is a gdb-dashboard problem, but I wonder if it is.
I use gdb-dashboard everyday on ARM embedded targets with a JLink probe (JLinkGDBServer). I use
```
	dashboard variables -output /dev/pts/$arg0
	dashboard source -output /dev/pts/$arg1
	dashboard source -style height $arg3
	dashboard assembly -output /dev/pts/$arg2
	dashboard assembly -style height $arg3
```
to split the display across different ttys (in tmux). I do lengthy gdb sessions (the same gdb instance runs for days).

The issue is not too frequent. Here's its latest occurrence when I hit ^C to stop my target:
```
^C
Program received signal SIGTRAP, Trace/breakpoint trap.
[... /* dashboard display */ ...]
/home/tcwg-buildslave/workspace/tcwg-make-release_0/snapshots/binutils-gdb.git~gdb-8.2-branch/gdb/inline-frame.c:156: internal-error: void inline_frame_this_id(frame_info*, void**, frame_id*): Assertion `frame_id_p (*this_id)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) y

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

/home/tcwg-buildslave/workspace/tcwg-make-release_0/snapshots/binutils-gdb.git~gdb-8.2-branch/gdb/inline-frame.c:156: internal-error: void inline_frame_this_id(frame_info*, void**, frame_id*): Assertion `frame_id_p (*this_id)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```
Here's the gdb version I use:
```
[~] /opt/toolchains/armv7-gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gdb --version                                                                
GNU gdb (Linaro_GDB-2019.02) 8.2.1.20190122-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Anybody got this?

I'm not using master. My last update was end of August 2019. I'll update now and confirm that it still happens.

**Comment by cyrus-and** [comment] 2020-02-21 10:02
Well even if this is caused by the dashboard this is still a GDB issue (as the message states) IMHO; one shouldn't be able to crash GDB or cause the above from the Python API.

Of course I understand that trying to reproduce it without the dashboard could be pretty hard. Feel free to post more information so I can try to reproduce it.

> I use gdb-dashboard everyday

I'm so glad to hear that! :)

**Comment by cyrus-and** [comment] 2020-06-01 19:40
Closing since there's nothing I can do about this.

**Closed by cyrus-and** 2020-06-01 19:40 UTC
Labels: external issue, irreproducible
