### ISSUE TITLE
Continuing in breakpoint commands hangs gdb if dashboard is enabled

### ISSUE THREAD

**Issue by jordan9001** [cyrus-and/gdb-dashboard#218] opened 2020-10-01 11:46 UTC
Continuing in breakpoint commands hangs gdb if dashboard is enabled. You can verify this by doing the following in gdb on a sample program:
```
b main
commands
cont
end
run
```
The error that gets raised is `gdb.error: Selected thread is running.` and then gdb will be unresponsive. 
Maybe this is a duplicate of old issue #27
Thanks

**Comment by jordan9001** [comment] 2020-10-01 12:53
I have fixed this by modifying dashboard, but I don't think the fix is robust enough to want to issue a pull request.
I have two fixes. The first one I don't think is as robust, but seems to work
My fix changes on_stop from:
```
def on_stop(self, _):
        if self.is_running():
            self.render(clear_screen=False)
```
to
```
def on_stop(self, e):
        if isinstance(e, gdb.BreakpointEvent) and len(e.breakpoints) > 0:
                for b in e.breakpoints:
                        if b.commands is None:
                                continue
                        for l in b.commands.split('\n'):
                                cmd = l.split()[0].lower()
                                if cmd.startswith("cont") or cmd == "c":
                                        return
        if self.is_running():
            self.render(clear_screen=False)
```
but I am sure there are lots of cases that it is not covering.

The second case seems like it could catch more cases, but messes up the ordering so that the prompt comes before the dashboard output, and might have other implications

For the second version of the fix I changed on_stop from:
```
def on_stop(self, _):
        if self.is_running():
            self.render(clear_screen=False)
```
to
```
def do_render(self):
        if self.is_running():
            self.render(clear_screen=False)

def on_stop(self, _):
        gdb.post_event(self.do_render)
```

**Comment by cyrus-and** [comment] 2020-10-01 12:56
I suspect this is kind of a bug in GDB, basically this happens:

1. the program runs (`gdb.events.cont` received);

2. the program stops at the breakpoint (`gdb.events.stop` **NOT** received yet);

3. breakpoint commands are executed, including `cont` (`gdb.events.cont` received);

4. the `gdb.events.stop` event is now received and the dashboard is rendered, but the program is actually not stopped, hence the issue.

Let me dig into it...

**Comment by cyrus-and** [comment] 2020-10-01 13:20
Yet it's not clear to me what actually causes the hanging.

**Comment by cyrus-and** [comment] 2020-10-10 14:14
OK, using the following as a `.gdbinit` instead of the dashboard is enough to reproduce the issue in the conditions provided by the OP.

```
python gdb.events.stop.connect(lambda _: gdb.execute('echo'))
```

And I'm using `gdb.execute` in several places in the dashboard, hence the hanging...

This is clearly a GDB bug, I've wasted my time before filing bug to them with no avail but if someone is willing to report this, feel free to use the information present in this thread to do so, and also to link back the issue here.

**Comment by cyrus-and** [comment] 2020-10-10 15:08
Closing for now, since I cannot really do anything about it. I'm open to suggestions...

**Closed by cyrus-and** 2020-10-10 15:08 UTC
Labels: external issue

**Comment by algrebe** [comment] 2021-03-30 21:56
@cyrus-and I faced this too and came up with the following - 

I added a command `dashboard -eat-breakpoint` which would ignore the next stop event and cont event.

So given the example from above 
```
b main
commands
dashboard -eat-breakpoint # <--- Users have to add this to their commands so that it works
cont
end
run
```

```python
class EatBreakpointEvent(gdb.Command):
     def __init__(self, dashboard):
         gdb.Command.__init__(self, 'dashboard -eat-breakpoint', gdb.COMMAND_USER)
         self.dashboard = dashboard
 
     def invoke(self, arg, from_tty):
         self.dashboard.eat_breakpoint_event()

class Dashboard(gdb.Command):
    def __init__(self):
        .....
        Dasboard.EatBreakpointCommand(self)
        self.eat_breakpoint_stop_event = 0
        self.eat_breakpoint_cont_event = 0

    def eat_breakpoint_event(self):
        self.eat_breakpoint_cont_event += 1
        self.eat_breakpoint_stop_event += 1

    def on_continue(self, _):
        if self.eat_breakpoint_cont_event > 0:
            self.eat_breakpoint_cont_event -= 1
            return
        ....

    def on_stop(self, _):
        if self.eat_breakpoint_stop_event > 0:
            self.eat_breakpoint_stop_event -= 1
            return
    ....
```

At this point it doesn't hang, the process still continues but it still prints out the dashboard and I'm not sure how to fix that. i.e. The source, variables, threads etc are displayed on the screen even though I "return". Was wondering if you could point me to other places that I need to `return` from as well, so that it's as if the dashboard were never activated on breakpoint.

If you feel that this is worth adding into the repo as a fix, I'd be happy to make it a pull request. (*I love this dashboard, thank you for it!*)

**Comment by cyrus-and** [comment] 2021-04-03 09:21
@algrebe that's a neat idea, but it apparently doesn't work. What happen after the `run` command in the OP's example is (kind of contrary on what I said [before](https://github.com/cyrus-and/gdb-dashboard/issues/218#issuecomment-702115396)...?):

1. `gdb.events.cont` received: `Output/messages` rendered;

2. `gdb.events.stop` received: dashboard rendered;

3. the rendering of the dashboard eventually invokes a `gdb.execute(...)`, this has the effect of *switching* to the execution of the breakpoint's commands;

4. the `continue` is executed and another `gdb.events.cont` is received: `Output/messages` rendered again;

5. only now the rendering continues, but the program is running (hence the errors) and GDB hangs (and it doesn't hang due to the errors).

So your solution of incrementing a counter inside the breakpoint commands happens too late. Or maybe I'm misunderstanding something, can you please send me the diff of your solution?

**Comment by algrebe** [comment] 2021-04-04 01:30
@cyrus-and Thank you for your response. Yes, it does happen too late.  So I took another approach this time - rather than having `cont` in the command, I ask the dashboard to issue the `cont`. This seems to work well. It probably isn't a fix to handling cont from commands but it's a good workaround for those who use the dashboard.

```bash
b foo
commands
dashboard -cont # <--- instead of using cont, use dashboard -cont
end
```

```
diff --git a/.gdbinit b/.gdbinit
index 8c3db0a..db5050b 100644
--- a/.gdbinit
+++ b/.gdbinit
@@ -400,6 +400,7 @@ class Dashboard(gdb.Command):
         Dashboard.OutputCommand(self)
         Dashboard.EnabledCommand(self)
         Dashboard.LayoutCommand(self)
+        Dashboard.ContinueCommand()
         # setup style commands
         Dashboard.StyleCommand(self, 'dashboard', R, R.attributes())
         # main terminal
@@ -824,6 +825,13 @@ configuration files must be placed.'''
             if output:
                 fs.write('{} -output {}\n'.format(prefix, output))
 
+    class ContinueCommand(gdb.Command):
+        def __init__(self):
+            gdb.Command.__init__(self, 'dashboard -cont', gdb.COMMAND_USER)
+
+        def invoke(self, arg, from_tty):
+            gdb.post_event(lambda: gdb.execute("cont"))
+
     class OutputCommand(gdb.Command):
         '''Set the output file/TTY for the whole dashboard or single modules.
 

```

**Comment by cyrus-and** [comment] 2021-04-04 08:31
@algrebe OK it works, thanks!

So apparently *scheduling* a continuation command avoids the hanging. I also noticed that rendering the dashboard in a `gdb.post_event` handler also works but it messes with the prompt.

It's still suboptimal as the dashboard shouldn't be rendered in such conditions (hardly noticeable if the scrollback is discarded, default) but at least it doesn't force the users to kill their debugging session. Anyway since this is something that requires user intervention anyway, I prefer to document this in the wiki for now and suggest to define a custom command to be used when continuing within a breakpoint's command list:

```gdb
define continue-breakpoint
python gdb.post_event(lambda: gdb.execute('continue'))
end
```

The usage is the following:

```
b main
commands
echo from breakpoint
continue-breakpoint
end
```

See the corresponding [wiki page](https://github.com/cyrus-and/gdb-dashboard/wiki/Continue-from-the-breakpoint-command-list).
